# Autogenerated tests with OpenCode

import unittest
from main import suffix, sardinas_patterson


class TestSuffix(unittest.TestCase):
    def test_suffix_returns_remaining_string(self):
        self.assertEqual(suffix("hello", "he"), "llo")

    def test_suffix_returns_empty_when_exact_match(self):
        self.assertEqual(suffix("hello", "hello"), "")

    def test_suffix_returns_none_when_no_prefix(self):
        self.assertIsNone(suffix("hello", "world"))


class TestSardinasPatterson(unittest.TestCase):
    def test_instantaneous_code_is_uniquely_decodable(self):
        codes = ["0", "10", "11"]
        self.assertTrue(sardinas_patterson(codes))

    def test_single_code_is_uniquely_decodable(self):
        codes = ["0"]
        self.assertTrue(sardinas_patterson(codes))

    def test_duplicate_code_is_not_uniquely_decodable(self):
        codes = ["0", "0"]
        self.assertFalse(sardinas_patterson(codes))

    def test_classic_nonisstantaneous_code(self):
        codes = ["ab", "b"]
        self.assertTrue(sardinas_patterson(codes))

    def another_test(self):
        codes = ["01", "10", "011"]
        self.assertTrue(sardinas_patterson(codes))


if __name__ == "__main__":
    unittest.main()
